### ISSUE TITLE
Unlearn Method

### ISSUE THREAD

**Issue by ghost** [jpmorganchase/i2i-generator-unlearning#2]
I couldn't find any relevant 'unlearn' method in your code. Did you move the code for that method elsewhere?

**Comment by leefly072** [comment]
I also have the same question and am unsure if it's convenient to answer. Thank you.

**Comment by chunfuchen** [comment]
Hi, as instructed in the README, please clone other repos that contains the unlearning codes. 
https://github.com/jpmorganchase/i2i-generator-unlearning?tab=readme-ov-file#installation

**Comment by chunfuchen** [comment]
Closed it as how to get unlearn method is described in the installation section. Please feel free to reopen it if there is an issue regarding the unlearn method.
